version: "3.8"

services:
  app:
    build: .
    container_name: credit-risk-app
    volumes:
      - .:/app                # Mount project folder inside container
    working_dir: /app
    command: python src/api/main.py  # default command
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "5000:5000"          # Optional: if you later run FastAPI

  jupyter:
    build: .
    container_name: credit-risk-jupyter
    volumes:
      - .:/app
    working_dir: /app
    command: jupyter notebook --ip=0.0.0.0 --port=8888 --allow-root --no-browser
    ports:
      - "8888:8888"
    environment:
      - PYTHONUNBUFFERED=1
